language: node_js
node_js: "6"
sudo: false

cache:
  yarn: true

matrix:
  include:
    - name: "Basic test"
      env:
        - JOB_TYPE=basic
    - name: "Windows-specific test (using x86)"
      os: windows
      env:
        - JOB_TYPE=win-x86
        - TEST_IGNORE_256_ICON=1
        - YARN_GPG=no # workaround
    - name: "Windows-specific test (using x64)"
      os: windows
      env:
        - JOB_TYPE=win-x64
        - TEST_IGNORE_256_ICON=1
        - YARN_GPG=no # workaround
  fast_finish: true

script: yarn run test:$JOB_TYPE
